module.exports = {
    contractABI: [{"inputs":[{"internalType":"string","name":"name","type":"string"},{"internalType":"string","name":"account","type":"string"},{"internalType":"string","name":"password","type":"string"},{"internalType":"string","name":"note","type":"string"}],"name":"create","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"uint256","name":"","type":"uint256"}],"name":"datas","outputs":[{"internalType":"uint256","name":"id","type":"uint256"},{"internalType":"string","name":"name","type":"string"},{"internalType":"string","name":"account","type":"string"},{"internalType":"string","name":"password","type":"string"},{"internalType":"string","name":"note","type":"string"},{"internalType":"uint256","name":"timestamp","type":"uint256"},{"internalType":"bool","name":"isValid","type":"bool"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"uint256","name":"id","type":"uint256"}],"name":"deleteData","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[],"name":"nextId","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"uint256","name":"id","type":"uint256"}],"name":"read","outputs":[{"internalType":"uint256","name":"","type":"uint256"},{"internalType":"string","name":"","type":"string"},{"internalType":"string","name":"","type":"string"},{"internalType":"string","name":"","type":"string"},{"internalType":"string","name":"","type":"string"},{"internalType":"uint256","name":"","type":"uint256"},{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"uint256","name":"id","type":"uint256"},{"internalType":"string","name":"name","type":"string"},{"internalType":"string","name":"account","type":"string"},{"internalType":"string","name":"password","type":"string"},{"internalType":"string","name":"note","type":"string"},{"internalType":"bool","name":"isValid","type":"bool"}],"name":"update","outputs":[],"stateMutability":"nonpayable","type":"function"}],
    // Contract Address
    contractAddress: '0xf1247E4671C945718aDD657E9DD3dCD57120A6e3',
    // Account Address
    data: {
        from: '0x9bC8A198018502e5565F648f8D2692f436e57a96', // Ethereum Account Address
        gasPrice: '20000000000', // Gas Price
        gas: '6721975', // Gas Limit
    }
}